package info.sjd;

import java.util.List;
import java.util.logging.Logger;

import info.sjd.service.AppendFile;
import info.sjd.service.DelOldRecords;
import info.sjd.service.FileAccess;
import info.sjd.service.ThreadWrite333;

/**
 * 
 * @author Vitaliy-tyma
 * 
 *
 *         DATA INPUT/OUTPUT
 * 
 *         DONE Create class for data saving process about server connection
 *         with the following fields: time (current system time), session and
 *         IP.
 * 
 *         DONE Create list of 10 instances of this class through implementation
 *         of log recordings
 * 
 *         DONE Fields are to be generated by your own, better to implement own
 *         randomizer for values range.
 * 
 *         DONE Record data from the list into TXT file in LOG folder inside of
 *         the project.
 * 
 *         DONE Previous records in the file must be preserved.
 * 
 *         DONE As a result file has to contain such data: 1529666255304
 *         123456789 128.158.234.15 1529666289304 123456799 123.148.214.19 …
 *         First column is time in milliseconds, Second - session (random
 *         9-digits number), Third - IP (also is created by randomly).
 * 
 * 
 *         DONE Implement logs recording
 * 
 *         DONE Implement connections logs reading from this file for some
 *         period
 * 
 *         DONE Implement logs deleting from files older then 3 days.
 * 
 */
/**
 * MULTITHREADING
 * 
 * 
 * 
 * */

public class AppRunner {

	/* MAIN ****************************************1/
	public static void main(String[] args) {

		/** INITIALISATION */
		String DIR_NAME = "log/";
		String FILE_NAME = DIR_NAME + "task09.txt";

		
		
		
		/** (VOID) Save logs to file. */
		//AppendFile.appendFile(FILE_NAME);
		for (int i = 0 ; i < 3; i++) {
			ThreadWrite333.threadWrite333(FILE_NAME);
		}
		
		
		
		/** (List<String>) Read logs from log-file. */
		//List<String> lines = FileAccess.readFromFile(FILE_NAME);
		/** Demo of usage of readFromFile method. */
		/*Logger logger = Logger.getLogger(AppRunner.class.getName());
		for (String line : lines) {
			logger.info(line);
		}*/

		
		
		
		/** (VOID) Delete more then 3 days old records from the log-file. */
		//DelOldRecords.delOldRecords(FILE_NAME);

	}

}